# =========== seq_36_pred_24 =============

python -u run_open_net.py \
  --is_training 1 \
  --root_path ./dataset/illness/ \
  --data_path national_illness.csv \
  --model_id illness_36_24 \
  --model B6iFast \
  --data custom \
  --features M \
  --seq_len 36 \
  --label_len 18 \
  --pred_len 24 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 1 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --stride 8 \
  --kernel_size 25 \
  --des 'normal_0' \
  --n_learner 3 \
  --urt_heads 1 \
  --learning_rate 0.00009 \
  --d_model 512 \
  --d_ff 512 \
  --global_freq_pred 0 \
  --itr 1 \
  --fix_seed 2021 \
  --train_epochs 20 \
  --batch_size 16 \
  --patience 3 \
  --period_list 24 36 \
  --dropout 0.1 \
  --lradj type3 \
  --checkpoints ./checkpoints/

# =========== seq_36_pred_36 =============

python -u run_open_net.py \
  --is_training 1 \
  --root_path ./dataset/illness/ \
  --data_path national_illness.csv \
  --model_id illness_36_36 \
  --model B6iFast \
  --data custom \
  --features M \
  --seq_len 36 \
  --label_len 18 \
  --pred_len 36 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 1 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --stride 8 \
  --kernel_size 25 \
  --des 'normal_0' \
  --n_learner 3 \
  --urt_heads 1 \
  --learning_rate 0.00009 \
  --d_model 512 \
  --d_ff 512 \
  --global_freq_pred 0 \
  --itr 1 \
  --fix_seed 2021 \
  --train_epochs 20 \
  --batch_size 16 \
  --patience 3 \
  --period_list 24 36 \
  --dropout 0.1 \
  --lradj type3 \
  --checkpoints ./checkpoints/

# =========== seq_36_pred_48 =============

python -u run_open_net.py \
  --is_training 1 \
  --root_path ./dataset/illness/ \
  --data_path national_illness.csv \
  --model_id illness_36_48 \
  --model B6iFast \
  --data custom \
  --features M \
  --seq_len 36 \
  --label_len 18 \
  --pred_len 48 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 1 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --stride 8 \
  --kernel_size 25 \
  --des 'normal_0' \
  --n_learner 3 \
  --urt_heads 1 \
  --learning_rate 0.00009 \
  --d_model 512 \
  --d_ff 512 \
  --global_freq_pred 0 \
  --itr 1 \
  --fix_seed 2021 \
  --train_epochs 20 \
  --batch_size 16 \
  --patience 3 \
  --period_list 24 36 \
  --dropout 0.1 \
  --lradj type3 \
  --checkpoints ./checkpoints/

  # =========== seq_36_pred_60 =============

python -u run_open_net.py \
  --is_training 1 \
  --root_path ./dataset/illness/ \
  --data_path national_illness.csv \
  --model_id illness_36_60 \
  --model B6iFast \
  --data custom \
  --features M \
  --seq_len 36 \
  --label_len 18 \
  --pred_len 60 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 1 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --stride 8 \
  --kernel_size 25 \
  --des 'normal_0' \
  --n_learner 3 \
  --urt_heads 1 \
  --learning_rate 0.00009 \
  --d_model 512 \
  --d_ff 512 \
  --global_freq_pred 0 \
  --itr 1 \
  --fix_seed 2021 \
  --train_epochs 20 \
  --batch_size 16 \
  --patience 3 \
  --period_list 24 36 \
  --dropout 0.1 \
  --lradj type3 \
  --checkpoints ./checkpoints/